import mongoose from 'mongoose';

export const UserSchema = new mongoose.Schema({
  username: { type: String },
  password: { type: String },
  email: { type: String },
  type: { type: mongoose.Schema.Types.ObjectId, ref: 'UserType' },
  imagePath: { type: String },
  stu: { type: {
    firstName: { type: String },
    lastName: { type: String },
    phone: { type: Number },
    year: { type: Number },
    graduated: { type: Boolean },
    applications: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Concourse' }],
    cvUploaded: { type: Boolean },
    cv: { type: {
      firstName: { type: String },
      lastName: { type: String },
      address: { type: String },
      postalCode: { type: String },
      city: { type: String },
      county: { type: String },
      phone: { type: Number },
      email: { type: String },
      website: { type: String },
      applicationType: { type: String },
      work: [{ type: {
        fromDate: { type: Date },
        toDate: { type: Date },
        position: { type: String },
        employer: { type: String },
        city: { type: String },
        county: { type: String },
        description: { type: String },
      } }],
      education: [{ type: {
        fromDate: { type: Date },
        toDate: { type: Date },
        qualificaton: { type: String },
        school: { type: String },
        city: { type: String },
        county: { type: String },
        description: { type: String },
      } }],
      motherTonque: { type: String },
      foreignTonque: [{ type: String }],
      communicationSkills: { type: String },
      organisationalSlills: { type: String },
      jobRelatedSkills: { type: String },
      digitalSkills: { type: String },
    } },
  } },
  com: { type: {
    name: { type: String },
    city: { type: String },
    director: { type: String },
    taxNumber: { type: String },
    employees: { type: Number },
    website: { type: String },
    industry: { type: mongoose.Schema.Types.ObjectId, ref: 'Industry' },
    field: { type: String },
    concourses: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Concourse' }],
  } }, 
  adm: { type: {
    firstName: { type: String },
    lastName: { type: String },
    phone: { type: Number },
  } }, 
});

export const User = mongoose.model('User', UserSchema);
